/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rbboHkbHgS9
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Footer from "./footer";
import Header from "./header";

export function CreateSubject() {
  return (
    <div className="flex flex-col h-screen">
      <Header></Header>
      <main className="flex-1 grid place-items-center py-6 overflow-y-auto m-4">
        <div className="mx-4 md:mx-6 w-full max-w-sm space-y-4">
          <div className="space-y-2 text-center">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl">
              Subscribe to our Newsletter
            </h1>
            <p className="text-gray-500 dark:text-gray-400">
              Sign up to receive updates on new components, features, and
              resources.
            </p>
          </div>
          <div className="space-y-2 w-full max-w-xs mx-auto">
            <Input
              className="w-full max-w-lg mx-auto"
              placeholder="Enter your email"
              type="email"
            />
            <Button className="w-full max-w-xs mx-auto">Subscribe</Button>
          </div>
        </div>
      </main>
      <Footer></Footer>
    </div>
  );
}
