/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZFRegHGET9U
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import { authService } from "../../services/auth";

export function Login() {
  const [account, setAccount] = useState("");
  const [password, setPassword] = useState("");
  const changeAccount = (event) => {
    setAccount(event.target.value);
  };
  const changePassword = (event) => {
    setPassword(event.target.value);
  };

  const router = useRouter();

  async function signIn() {
    const { token } = await authService.signIn(account, password);
    localStorage.setItem("accessToken", token);
    router.push("/");
  }

  async function signUp() {
    const { token } = await authService.signUp(account, password);
    localStorage.setItem("accessToken", token);
    router.push("/");
  }

  return (
    <div className="flex items-center min-h-screen px-6 justify-center w-full">
      <div className="grid max-w-sm gap-6 w-full mx-auto">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">欢迎</h1>
          <p className="text-gray-500 dark:text-gray-400">大驾光临 有失远迎</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">账号</Label>
            <Input
              id="email"
              placeholder="m@example.com"
              required
              type="text"
              onChange={changeAccount}
            />
          </div>
          <div className="space-y-2">
            <div className="flex items-center">
              <Label htmlFor="password">密码</Label>
              <Link className="ml-auto inline-block text-sm underline" href="#">
                忘记密码?
              </Link>
            </div>
            <Input
              id="password"
              required
              type="password"
              onChange={changePassword}
            />
          </div>
          <Button className="w-full" onClick={signIn}>
            登录
          </Button>
          <Button className="w-full" variant="outline" onClick={signUp}>
            注册
          </Button>
        </div>
      </div>
    </div>
  );
}
