/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RyVRRmrEDSA
 */
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export function Trending() {
  return (
    <Card className="flex-1 w-full max-w-lg overflow-y-auto">
      <CardHeader className="pb-0">
        <CardTitle className="text-lg">Rank</CardTitle>
        <CardDescription>Top contributors</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <span className="font-semibold">1.</span>
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="Grace" src="/placeholder-user.jpg" />
                <AvatarFallback>GR</AvatarFallback>
              </Avatar>
            </div>
            <div className="grid gap-0.5 text-sm">
              <div className="font-semibold">Grace Lee</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Best coder
              </div>
            </div>
          </div>
          <div className="font-semibold text-sm w-12 text-right">950</div>
        </div>
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <span className="font-semibold">2.</span>
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="Ethan" src="/placeholder-user.jpg" />
                <AvatarFallback>ET</AvatarFallback>
              </Avatar>
            </div>
            <div className="grid gap-0.5 text-sm">
              <div className="font-semibold">Ethan Harris</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Bug squasher
              </div>
            </div>
          </div>
          <div className="font-semibold text-sm w-12 text-right">840</div>
        </div>
      </CardContent>
    </Card>
  );
}
